# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GolangCliTemplate < Formula
  desc "A Golang cli template."
  homepage "https://github.com/thazelart/golang-cli-template"
  version "1.0.0"
  license "Apache 2.0"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thazelart/golang-cli-template/releases/download/v1.0.0/golang-cli-template_darwin_x86_64.tar.gz"
      sha256 "4e33e26af480b25416cbf7fa2728fab3f4a14134520e147fd360eb3085079105"

      def install
        bin.install "golang-cli-template"
        bash_completion.install "completions/golang-cli-template.bash" => "golang-cli-template"
        zsh_completion.install "completions/golang-cli-template.zsh" => "_golang-cli-template"
        fish_completion.install "completions/golang-cli-template.fish"
        man1.install "manpages/golang-cli-template.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thazelart/golang-cli-template/releases/download/v1.0.0/golang-cli-template_darwin_arm64.tar.gz"
      sha256 "c43d28cfc8cca0d647e17e0aaa5f7eda03320ef8ab2ccaf6e7ce30b84d4b98a3"

      def install
        bin.install "golang-cli-template"
        bash_completion.install "completions/golang-cli-template.bash" => "golang-cli-template"
        zsh_completion.install "completions/golang-cli-template.zsh" => "_golang-cli-template"
        fish_completion.install "completions/golang-cli-template.fish"
        man1.install "manpages/golang-cli-template.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/thazelart/golang-cli-template/releases/download/v1.0.0/golang-cli-template_linux_armv7.tar.gz"
      sha256 "b1511a6e9290c9f3be681c54f3bc4c24086e2cfeb32584f710f064ffed82edd5"

      def install
        bin.install "golang-cli-template"
        bash_completion.install "completions/golang-cli-template.bash" => "golang-cli-template"
        zsh_completion.install "completions/golang-cli-template.zsh" => "_golang-cli-template"
        fish_completion.install "completions/golang-cli-template.fish"
        man1.install "manpages/golang-cli-template.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thazelart/golang-cli-template/releases/download/v1.0.0/golang-cli-template_linux_arm64.tar.gz"
      sha256 "4872fc67705585910c82513547e20d408b14df9c6641b24c9ef55da6605ad366"

      def install
        bin.install "golang-cli-template"
        bash_completion.install "completions/golang-cli-template.bash" => "golang-cli-template"
        zsh_completion.install "completions/golang-cli-template.zsh" => "_golang-cli-template"
        fish_completion.install "completions/golang-cli-template.fish"
        man1.install "manpages/golang-cli-template.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/thazelart/golang-cli-template/releases/download/v1.0.0/golang-cli-template_linux_x86_64.tar.gz"
      sha256 "3353747ab0dc4eef8523e87cc83a65b5bad028ab7aad4bfa6007bac64b666624"

      def install
        bin.install "golang-cli-template"
        bash_completion.install "completions/golang-cli-template.bash" => "golang-cli-template"
        zsh_completion.install "completions/golang-cli-template.zsh" => "_golang-cli-template"
        fish_completion.install "completions/golang-cli-template.fish"
        man1.install "manpages/golang-cli-template.1.gz"
      end
    end
  end

  test do
    system "#{bin}/golang-cli-template version"
  end
end
